### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Yveaux** [107-systems/107-Arduino-littlefs#13]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: Bug Report

Code won't compile; spurious characters found at https://github.com/107-systems/107-Arduino-littlefs/blob/96cc90b5b54947708adc2f19d7358c19114d7e29/src/littlefs-v2.5.1/lfs.c#L5766

**Minimum configuration to replicate the bug**
* PlatformIO
*  framework-arduinopico @ 1.30301.0+sha.3cc5ac1
* tool-rp2040tools @ 1.0.2
* toolchain-rp2040-earlephilhower @ 5.100300.230216 (10.3.0)
* 107-Arduino-littlefs 0.5.0

Prepared a PR to fix: #12

**Comment by aentinger** [comment]
Fixed by #12 .
