### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Yveaux** [107-systems/107-Arduino-littlefs#15]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: Bug Report
Fields in lfs_config that are not set explicitly by FilesystemConfig c'tor, will not receive a default value and cause issues later on.

```C++
#include <Arduino.h>
#include <107-Arduino-littlefs.h>

static littlefs::FilesystemConfig filesystem_config
  (
     // ....
  )

void setup()
{
    // ...
    auto const cfg = filesystem_config.raw_cfg();

    filesystem_config = littlefs::FilesystemConfig(cfg.read, cfg.prog, cfg.erase, cfg.sync,
                            1, 1, 4096, 10, cfg.block_cycles, cfg.cache_size, cfg.lookahead_size);

    // now _cfg.metadata_max in filesystem_config contains garbage, causing
    // lfs.c, line 3992: LFS_ASSERT(lfs->cfg->metadata_max <= lfs->cfg->block_size); to fail

    littlefs::Filesystem filesystem(filesystem_config);
    // ...
}
```

**Minimum configuration to replicate the bug**

- PlatformIO
- framework-arduinopico @ 1.30301.0+sha.3cc5ac1
- tool-rp2040tools @ 1.0.2
- toolchain-rp2040-earlephilhower @ 5.100300.230216 (10.3.0)
- 107-Arduino-littlefs 0.5.0

Prepared a PR to fix: https://github.com/107-systems/107-Arduino-littlefs/pull/14

**Comment by aentinger** [comment]
Please use a proper title for the issue report in the future.

Fixed by #14 .
